version: '3.8'

services:
  postgres-heroes:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${HERO_DB_USER}
      POSTGRES_PASSWORD: ${HERO_DB_PASSWORD}
      POSTGRES_DB: ${HERO_DB_NAME}
      POSTGRES_DATABASE_URL: ${HERO_DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - postgres_heroes_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./superhero-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    depends_on:
      - postgres-heroes
    volumes:
      - uploads:/usr/src/app/public/uploads
    command: sh -c "npm run wait-for-db && npm run db:push && npm run start:prod"

  frontend:
    build:
      context: ./superhero-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_DOCKER_API_URL=${NEXT_DOCKER_API_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

volumes:
  postgres_heroes_data:
  uploads: